title: Recipe

pages: false

files:
  fields:
    focus:
      label: Focus Crop
      type: focus

fields:
  title:
    label: Title
    type:  text

  image:
    label: Image
    type:  image

  video:
    label: Video (Optional)
    type: video

  recipeMixer:
    label: Q Mixer
    type: select
    options: query
    query:
      page: mixers/

  ingredients:
    label: Ingredients
    type: builder
    fieldsets:
      ingredient:
        label: Add Ingredient
        fields:
          ingredient:
            label: Add Ingredient
            type: text

  servings:
    label: Serving <span class="panel-field-description">Text Description like "Serves one glass"</span>
    type: text
    width: 1/2

  servingsNumber:
    label: Serves <span class="panel-field-description">Should be a number like "01"</span>
    type: number
    width: 1/2

  method:
    label: Method
    type: textarea
    buttons: false

  variations:
    label: Variations
    type: textarea
    buttons: false
